### PR TITLE
Added linux-musl support

### PR DESCRIPTION
**Pull request by petermz**
Hi,
The only thing that prevents fastr from building on musl is the `#include "fpu_control.h"` line somewhere in libf2c sources. This header file is missing in musl. I'm adding this (effectively empty) header file as a patch to `f2c/libf2c-patch`

### CODE REVIEW

**Comment by steve-s** [comment]
Hello, 

thank you for the PR. How does it work if the `extern __fpu_control` exposed by the glibc header is not there? Does linux-musl export it also but not in that header?

**Comment by petermz** [comment]
No, musl doesn't have it in its headers. My theory is that `__fpu_control` use sites are `#ifdef`'ed out and not compiled with musl

**Comment by steve-s** [comment]
Thanks for the explanation.

Have you signed the [Oracle Contributor Agreement](http://www.oracle.com/technetwork/community/oca-486395.html)? We use it to make the copyright of contributions clear. You can sign it at that link.

**Comment by petermz** [comment]
Hi,
I believe I should be covered by Bellsoft's umbrella OCA.

I've identified another undefined symbol and added it to unimplemented.c, hence the second commit. (It shows on musl because musl linkers use `-z now` by default, and libRnative fails to load).

**Comment by steve-s** [comment]
> I've identified another undefined symbol and added it to unimplemented.c, hence the second commit. (It shows on musl because musl linkers use -z now by default, and libRnative fails to load).

good, thanks. Could you please also add the standard Oracle GPL3 copyright that we use into the new file. Then I'll spin our internal tests and merge if these changes pass.

> I believe I should be covered by Bellsoft's umbrella OCA.

yes that should be OK, could you please give some proof that you're from that company (send me an e-mail from an account on that domain or add secondary e-mail here on GitHub)? Sorry I need to follow the procedures.

**Comment by petermz** [comment]
I already have `peter.zhelezniakov@bell-sw.com` as secondary email here, and I've just sent you an email from that address.
Added copyright header, too. Thanks!

**Comment by steve-s** [comment]
Ah, sorry I forgot that we're using prebuilt F2C in our CI and check that F2C still builts correctly only in post merge checks, which gave us this error:
```
In file included from ./fpu_control.h:26:
./fpu_control.h:26:2: warning: #include_next in file found relative to primary source file or found by absolute path; will search from start of include path [-Winclude-next-absolute-path]
#include_next "fpu_control.h"
 ^
./fpu_control.h:26:15: error: #include nested too deeply
#include_next "fpu_control.h"
              ^
199 warnings and 1 error generated.
make[2]: *** [makefile:30: uninit.o] Error 1
make[2]: Leaving directory 'fastr/libdownloads/f2c/src/libf2c'
make[1]: *** [Makefile:60: all] Error 2
make[1]: Leaving directory 'fastr/com.oracle.truffle.r.native/f2c'
make: *** [Makefile:70: all] Error 2
```

Seems that the `#include_next` did not work as expected?

**Comment by petermz** [comment]
Strange it didn't show in my testing, but now I can reproduce this. Does it sometimes work and sometimes not?

Also, how do you build using prebuilt F2C?

**Comment by steve-s** [comment]
Looking at it now, I think we have a bug in `com.oracle.truffle.r.native/f2c/Makefile` we do not clean the right `f2c` copy (there's one in `libdownloads` that mx downloads for us, and one in `f2c` top level dir, where we copy the former). So if you do `rm -rf f2c` and then `mx build` you should be actually building f2c from scratch.

In the same makefile you can see that we check for environment variable `F2C_BINARY` and if that's set we assume it points to pre-built f2c and we just copy it over and skip the building altogether.

**Comment by petermz** [comment]
I have a fix: #176

**Pull request merged**
