### PR TITLE
Implemented nlm

### PR DESCRIPTION
**Pull request by mardukbp**
This patch implements the R function `stats::nlm`. The only difference with respect to GNU-R is that I deleted all code related to printing from `uncmin.c` in order to avoid dealing with the includes for printing vectors.

I have not tested it extensively, but I think it is better to merge it to let people experiment with it.

### CODE REVIEW

**Comment by mardukbp** [comment]
Thanks Stepan! I will review it soon. Now I'm busy with the presentation for my thesis defense.

**Comment by steve-s** [comment]
Sure, best of luck with the defense.

**Comment by steve-s** [comment]
I've fixed the minor issues and merged the PR. Unfortunately, GitHub didn't pick that up, but your commit is here: ad8035c4a1d8385ce786ab373088c391d015c6ba. Thank you for your contribution!

**Comment by mardukbp** [comment]
Thank you Stepan for finishing this up.

Lately I've been busy with my new job in software quality assurance. I hope to use the skills I'm acquiring to improve FastR and other GraalVM-projects in the future.

**Pull request closed without merging**
